version: 0.0
os: linux
files:
  - source: /deploy/lab_2908/
    destination: /opt/lab_2908/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
